float:
  any:
  - name: neuralvault
    base_args: [angular]
    constructor: NeuralVault
    disabled: false
    docker_tag: neuralvault
    module: ann_benchmarks.algorithms.neuralvault
    run_groups:
      neuralvault:
        args: [null]
        query_args: [[10, 20, 40, 80, 100, 200, 400]]
